### ISSUE TITLE
关于 method setParams 的体验

### ISSUE THREAD

**Issue by virtuecai** [mricle/Mricode.Pagination#10]
很多情况下, 是在原有的param上进行部分参数的修改, 然后发请求. 
已存在setParam, 建议提供一个getParam, 
这样在海量的参数中, 一个获得原有的, 修改部分参数, 然后在set. 
因为在set中直接extend也不太好把控.

**Comment by virtuecai** [comment]
getParams: function () {
      return this.currentParams;
 },

**Comment by virtuecai** [comment]
只是一个示例代码, 待具体实现.

**Comment by mricle** [comment]
将在下个版本中实现

**Comment by liu-xinhui** [comment]
确实需要getParams方法，我现在就碰到了

**Comment by mricle** [comment]
v1.4.0 已增加getParams方法
