### ISSUE TITLE
bug 反馈

### ISSUE THREAD

**Issue by virtuecai** [mricle/Mricode.Pagination#11]
1. 配置了infoFormat: '{start} 至 {end} 条, 共 {total} 条', 但查询数据为0的条的适合, 显示的是: 0 entires
   2.当上一次请求返回为0条数据后, 再次切换条件查询, 出现; pageNumber = -1. 并且导致页数元素高亮没有.
2. 建议pageNumber 就从1开始, 而不是下标的概念. 服务端还得 + 1, 别扭.

**Comment by virtuecai** [comment]
0 entires 已找到参数, 之前忽略了.

**Comment by virtuecai** [comment]
现象:   -4 至 0 条, 共 62618 条

**Comment by virtuecai** [comment]
问题已找到, 临时解决方案: lastPageNum - 1 为0 时 -1 导致负数
218行: 
this.currentPageIndex = this.currentPageIndex > lastPageNum - 1 ? lastPageNum - 1 : this.currentPageIndex;
 if(this.currentPageIndex < 0) this.currentPageIndex = 0;

256行:
that.currentPageIndex = lastPageNum - 1;
 if(this.currentPageIndex < 0) this.currentPageIndex = 0;

**Comment by mricle** [comment]
感谢你的提醒，已解决pageIndex问题

**Comment by virtuecai** [comment]
接口返回值问题: $("#page").pagination('getPageIndex');
返回的并不是一个Number 数据, 而是 $page 对象.

**Comment by mricle** [comment]
已修复
