### ISSUE TITLE
交互体验 反馈

### ISSUE THREAD

**Issue by virtuecai** [mricle/Mricode.Pagination#12]
可以持续open状态, 用于反馈体验下的优化建议.

**Comment by virtuecai** [comment]
1.页面跳转文本框 input type 可以改为 type = 'number'

**Comment by virtuecai** [comment]
1. 输入跳转页数 超出范围后, 目前的体验是不跳转, 并清空文本框. 

2.1 建议: 最大页数为10也, 
2.1.1 当输入11页的时候不清空文本框, 而是让文本框 foucs, 并加入一个样式如: error什么的. 这样也利于不动源码定制.
2.1.1 当输入非法页数, 如 负数 -1, 字母等等非正整数的时候 ,可直接清空.

**Comment by mricle** [comment]
v1.4.0 已优化
