### ISSUE TITLE
不会用

### ISSUE THREAD

**Issue by tianjiqx** [mricle/Mricode.Pagination#15]
在IE和chrome上运行test例子都出现问题，chrome是指无法请求data.json。大概是url不支持。IE上莫名其妙说btn_search没有定义，删除后还是没有什么效果。真是分页插件都没一个简单好用的。

**Comment by lunix01** [comment]
chrome上用服务器环境呢

**Comment by tianjiqx** [comment]
很久以前的事情了，一个不知道什么问题了，后来我用的另外的插件，里面调用ajax方法，进行更新页面数据。插件：twbsPagination
