### ISSUE TITLE
设置pageSizeItems报错

### ISSUE THREAD

**Issue by codeTransfer** [mricle/Mricode.Pagination#18]
Uncaught TypeError: Cannot read property 'pageSizeItems' of undefined    **mricode.pagination.js:79**
我看了代码，这一行少了一对括号（粗体），应写成：
this.options.pageSizeItems = options.pageSizeItems || **(**($.fn.pagination.defaults && $.fn.pagination.defaults.pageSizeItems) ? $.fn.pagination.defaults.pageSizeItems : defaultOption.pageSizeItems**)**;

**Comment by mricle** [comment]
bug已修改;)
