### ISSUE TITLE
当前页从0开始,怎么从1开始呢

### ISSUE THREAD

**Issue by liu-xinhui** [mricle/Mricode.Pagination#7]
我们系统设计的是从第一页开始,没有第0页

**Comment by mricle** [comment]
用1.3.4.0版本，remote的pageParams 配置
remote: {
pageParams: function (data) {
return {
pageIndex: data.pageIndex + 1,
 pageSize: data.pageSize
}
},
}

+1 就是请求中的pageIndex从1开始

**Comment by liu-xinhui** [comment]
多谢
