### ISSUE TITLE
小量数据, 致命性体验 切换 pageSize

### ISSUE THREAD

**Issue by virtuecai** [mricle/Mricode.Pagination#8]
选择 pageSize 一页显示多少天数据体验(bug);

一共10条数据. 每页显示5条, 两页可以正常分页, 当选择pageSize为15后, 只有一页数据了, 但是, 分页组件不显示分页操作元素了,  只能重新查询或者刷新页面了. 体验不好, 建议就算只有一页, 不需要隐藏.

**Comment by virtuecai** [comment]
您的pagination我很早就关注了. 
this.$page.empty().hide();
this.$size.empty().hide();
this.$jump.empty().hide();
这块if逻辑建议性的考虑下.

**Comment by virtuecai** [comment]
还有一点,  关于元素顺序, 建议提供可配置顺序接口. 
在含有doc的版本中 , 我事这样处理的:
 remote: {
        pageElementSort: ['$info', '$size', '$page', '$jump'],
       //可选, 显示的先后顺序,
       // $info:"1 ~ 5条，共44条",  
       //'$size': pageSize, 
       //'$page', 'pageNumber', 
       //'$jump': 指定页面跳转
}

**Comment by mricle** [comment]
感谢你的建议，已在新版本中修改和增加配置
