### ISSUE TITLE
搜索后Jump框会消失

### ISSUE THREAD

**Issue by liu-xinhui** [mricle/Mricode.Pagination#9]
打开页面后是正常的
![temp1](https://cloud.githubusercontent.com/assets/7698511/12253923/88e414b0-b91e-11e5-949c-0a64c9e09fd4.png)

执行模糊搜索，无数据
![temp22](https://cloud.githubusercontent.com/assets/7698511/12253963/d62968ec-b91e-11e5-8d03-9cab3dd360f0.png)

删除模糊搜索关键字，出现数据，分页正常，但是Jump框消失
![temp2](https://cloud.githubusercontent.com/assets/7698511/12253930/9ae31062-b91e-11e5-9a54-d7f17dc203d1.png)

**Comment by liu-xinhui** [comment]
![image](https://cloud.githubusercontent.com/assets/7698511/12254001/2333b2be-b91f-11e5-925a-1f9311e3de83.png)
搜索时执行的代码

**Comment by lunix01** [comment]
这个问题没遇到，但是没有数据的时候，跳转没隐藏。

**Comment by mricle** [comment]
Jump消失问题请使用新版本，没有数据的时候显示问题已优化

**Comment by liu-xinhui** [comment]
@mricle 
![image](https://cloud.githubusercontent.com/assets/7698511/12283545/374d5444-b9e2-11e5-96b3-2d2dd7514906.png)
搜索后，jump框已经显示正常，但是页码显示不正常了，没有默认选中第一页

代码
![image](https://cloud.githubusercontent.com/assets/7698511/12283573/817f1340-b9e2-11e5-9fe4-fceeda44b936.png)

**Comment by mricle** [comment]
@liunewshine 测试下来没有复现搜索后没有选中的问题，你用的是哪个版本的？

**Comment by liu-xinhui** [comment]
@mricle 用的最新的1.3.6，昨天才下载的
直接搜索无问题，是在搜索无数据后，再次搜索有数据才会出现没有默认页号选中问题

![image](https://cloud.githubusercontent.com/assets/7698511/12313306/4d907ffa-baa1-11e5-8c6c-1a6a4cf38acd.png)

是不是这个地方-1导致的

**Comment by mricle** [comment]
@liunewshine 按你说的过程测试了一下还是没复现该问题

**Comment by mricle** [comment]
@liunewshine v1.3.7已解决第一页没选中的问题

**Comment by liu-xinhui** [comment]
已修复，非常感谢
